# Site settings
title: Enspiral Org Academy · 5-8 Sept 2019 · Belgium
email: phoebe@enspiral.com
description: 4-day residential training on decentralised organisation. An immersive learning experience to connect and practice with organisational adventurers from the future of work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
